/* eslint-disable */
// This file is auto-generated by scripts/update-scholar-citations.mjs
// Run manually with: npm run update:scholar

export const scholarCitationLastUpdatedIso: string | null = "2026-03-02T14:01:01.272Z";

export const scholarCitationsByPublicationId: Record<string, number | null> = {
  "enriching-ontologies-disjointness-llm-2024": 2,
  "pengquin-eswc-2024-paper": 0,
  "personalized-medicine-data-pods-2024": 3,
  "coliphages-human-urinary-microbiota-2023": 6,
  "cataloging-engineering-temperate-coliphages-2022": 0,
  "genome-investigation-urinary-gardnerella-2021": 9,
};
