/* eslint-disable */
// This file is auto-generated by scripts/update-scholar-citations.mjs
// Run manually with: npm run update:scholar

export const scholarCitationLastUpdatedIso: string | null = "2026-03-06T09:46:05.620Z";

export const scholarCitationsByPublicationId: Record<string, number | null> = {
  "genome-sharing-review-2026": 0,
  "disjointness-llm-ISWC-2024": 2,
  "wikidata-sparql-ISWC-2025": 0,
  "pengquin-eswc-2024": 0,
  "pm-pods-SWAT4HCLS-2024": 3,
  "TRIPLE-SWAT4HCLS-2024": 0,
  "urinary-coliphages-2023": 6,
  "engineering-coliphages-2022": 0,
  "gardnerella-characterization-2021": 9,
};

export const publicationDownloadsByPublicationId: Record<string, number | null> = {
  "genome-sharing-review-2026": null,
  "disjointness-llm-ISWC-2024": null,
  "wikidata-sparql-ISWC-2025": null,
  "pengquin-eswc-2024": null,
  "pm-pods-SWAT4HCLS-2024": null,
  "TRIPLE-SWAT4HCLS-2024": null,
  "urinary-coliphages-2023": null,
  "engineering-coliphages-2022": 167,
  "gardnerella-characterization-2021": null,
};
