/* eslint-disable */
// This file is auto-generated by scripts/update-scholar-citations.mjs
// Run manually with: npm run update:scholar

export const scholarCitationLastUpdatedIso: string | null = "2026-05-04T07:20:41.484Z";

export const scholarCitationsByPublicationId: Record<string, number | null> = {
  "google-scholar": null,
  "vcf-to-rdf-rml-swat4hcls-2026": 0,
  "genome-sharing-review-2026": 3,
  "disjointness-llm-ISWC-2024": 5,
  "wikidata-sparql-ISWC-2025": 1,
  "vcf2rdf-SWAT4HCLS-2025": null,
  "pengquin-eswc-2024": 0,
  "pm-pods-SWAT4HCLS-2024": 3,
  "TRIPLE-SWAT4HCLS-2024": 0,
  "urinary-coliphages-2023": 6,
  "engineering-coliphages-2022": 0,
  "gardnerella-characterization-2021": 10,
};

export const publicationDownloadsByPublicationId: Record<string, number | null> = {
  "google-scholar": null,
  "vcf-to-rdf-rml-swat4hcls-2026": null,
  "genome-sharing-review-2026": null,
  "disjointness-llm-ISWC-2024": null,
  "wikidata-sparql-ISWC-2025": null,
  "vcf2rdf-SWAT4HCLS-2025": null,
  "pengquin-eswc-2024": null,
  "pm-pods-SWAT4HCLS-2024": null,
  "TRIPLE-SWAT4HCLS-2024": null,
  "urinary-coliphages-2023": null,
  "engineering-coliphages-2022": 214,
  "gardnerella-characterization-2021": null,
};
