// This file is auto-generated by scripts/update-software-releases.mjs
// Run manually with: npm run update:software-releases

export interface SoftwareReleaseInfo {
  tagName: string | null;
  name: string | null;
  url: string | null;
  publishedAt: string | null;
}

export const softwareReleaseLastUpdatedIso: string | null = "2026-03-23T09:39:35.420Z";

export const softwareReleasesBySoftwareId: Record<string, SoftwareReleaseInfo | null> = {
  "genome-sharing-paper-webpage": null,
  "ldp-permissions-notifications-specification": null,
  "solid-cockpit": null,
  "sparql-view-materialization-containers": null,
  "vcf-rdfizer": null,
};
