// This file is auto-generated by scripts/update-software-releases.mjs
// Run manually with: npm run update:software-releases

export interface SoftwareReleaseInfo {
  tagName: string | null;
  name: string | null;
  url: string | null;
  publishedAt: string | null;
}

export const softwareReleaseLastUpdatedIso: string | null = "2026-08-13T11:44:35.673Z";

export const softwareReleasesBySoftwareId: Record<string, SoftwareReleaseInfo | null> = {
  "genome-sharing-paper-webpage": {
    tagName: null,
    name: "Latest update (main)",
    url: "https://github.com/ecrum19/GenomeSharingPaper_Webpage",
    publishedAt: "2026-03-19T11:59:08.000Z",
  },
  "ldp-permissions-notifications-specification": {
    tagName: null,
    name: "Latest update (main)",
    url: "https://github.com/ecrum19/ldp-permissions-notifications-specification",
    publishedAt: "2026-02-11T10:17:57.000Z",
  },
  "ontology-companion-generator": {
    tagName: "v1.1.1",
    name: "v1.1.1",
    url: "https://github.com/ecrum19/ocg/releases/tag/v1.1.1",
    publishedAt: "2026-08-13T07:56:36.000Z",
  },
  "qr-code-generator": {
    tagName: null,
    name: "Latest update (main)",
    url: "https://github.com/ecrum19/qr-code-generator",
    publishedAt: "2026-08-04T08:33:54.000Z",
  },
  "solid-cockpit": {
    tagName: "v1.3.0",
    name: "v1.3.0",
    url: "https://github.com/KNowledgeOnWebScale/solid-cockpit/releases/tag/v1.3.0",
    publishedAt: "2026-06-04T09:54:06.000Z",
  },
  "sparql-view-materialization-containers": {
    tagName: null,
    name: "Latest update (main)",
    url: "https://github.com/ecrum19/sparql-view-materialization-containers",
    publishedAt: "2026-02-03T09:02:44.000Z",
  },
  "vcf-rdfizer": {
    tagName: "v1.2.3",
    name: "v1.2.3",
    url: "https://github.com/ecrum19/VCF-RDFizer/releases/tag/v1.2.3",
    publishedAt: "2026-06-02T11:47:19.000Z",
  },
  "vord": {
    tagName: "v0.1",
    name: "v0.1",
    url: "https://github.com/ecrum19/vord/tree/v0.1",
    publishedAt: "2026-05-29T07:48:05.000Z",
  },
};
