/* eslint-disable */
// This file is auto-generated by scripts/build-slides.mjs
// Run: npm run build:slides

export interface TalkEntry {
  slug: string;
  title: string;
  sourceFile: string;
  dateIso: string;
  dateLabel: string;
  slidePath: string;
  posterPath?: string;
  posterTitle?: string;
}

export interface PosterEntry {
  slug: string;
  title: string;
  path: string;
}

export const talks: TalkEntry[] = [
  {
    slug: "sphn-290425",
    title: "SPHN 290425",
    sourceFile: "SPHN-290425.pdf",
    dateIso: "2025-04-29",
    dateLabel: "29/04/2025",
    slidePath: "/talks/slides/sphn-290425.pdf",
  },
  {
    slug: "vital-it-edc-040425",
    title: "Vital IT EDC 040425",
    sourceFile: "Vital-IT-EDC-040425.pdf",
    dateIso: "2025-04-04",
    dateLabel: "04/04/2025",
    slidePath: "/talks/slides/vital-it-edc-040425.pdf",
  },
  {
    slug: "edc-dph-25",
    title: "EDC DPH 25",
    sourceFile: "EDC-DPH-25.pdf",
    dateIso: "2025-01-01",
    dateLabel: "2025",
    slidePath: "/talks/slides/edc-dph-25.pdf",
  },
  {
    slug: "fwo24-pitch-edc-official",
    title: "FWO24 Pitch EDC(Official)",
    sourceFile: "FWO24_Pitch_EDC(official).pdf",
    dateIso: "2024-01-01",
    dateLabel: "2024",
    slidePath: "/talks/slides/fwo24-pitch-edc-official.pdf",
  },
  {
    slug: "isws2024-slytherin-presentation",
    title: "ISWS2024 Slytherin Presentation",
    sourceFile: "ISWS2024_Slytherin_Presentation.pdf",
    dateIso: "2024-01-01",
    dateLabel: "2024",
    slidePath: "/talks/slides/isws2024-slytherin-presentation.pdf",
  },
  {
    slug: "pengquin-eswc-2024",
    title: "PENGQUIN ESWC 2024",
    sourceFile: "PENGQUIN_ESWC_2024.pdf",
    dateIso: "2024-01-01",
    dateLabel: "2024",
    slidePath: "/talks/slides/pengquin-eswc-2024.pdf",
    posterPath: "/talks/posters/ESWC_24_Poster_EDC.pdf",
    posterTitle: "ESWC 24 Poster EDC",
  },
  {
    slug: "solidsymp2024-edc",
    title: "SolidSymp2024 EDC",
    sourceFile: "SolidSymp2024_EDC.pdf",
    dateIso: "2024-01-01",
    dateLabel: "2024",
    slidePath: "/talks/slides/solidsymp2024-edc.pdf",
  },
  {
    slug: "edc-18m-vito-jury",
    title: "EDC 18m VITO Jury",
    sourceFile: "EDC-18m-VITO-Jury.pdf",
    dateIso: "1900-01-01",
    dateLabel: "Undated",
    slidePath: "/talks/slides/edc-18m-vito-jury.pdf",
  },
  {
    slug: "sib-reflectionugent",
    title: "SIB ReflectionUGent",
    sourceFile: "SIB-ReflectionUGent.pdf",
    dateIso: "1900-01-01",
    dateLabel: "Undated",
    slidePath: "/talks/slides/sib-reflectionugent.pdf",
  },
  {
    slug: "solid-intro-triple",
    title: "Solid Intro TRIPLE",
    sourceFile: "Solid_intro_TRIPLE.pdf",
    dateIso: "1900-01-01",
    dateLabel: "Undated",
    slidePath: "/talks/slides/solid-intro-triple.pdf",
  },
  {
    slug: "swissprot",
    title: "SwissProt",
    sourceFile: "SwissProt.pdf",
    dateIso: "1900-01-01",
    dateLabel: "Undated",
    slidePath: "/talks/slides/swissprot.pdf",
  },
  {
    slug: "ugent-pengquin-intro",
    title: "UGent PENGQUIN Intro",
    sourceFile: "UGent_PENGQUIN_Intro.pdf",
    dateIso: "1900-01-01",
    dateLabel: "Undated",
    slidePath: "/talks/slides/ugent-pengquin-intro.pdf",
  },
];

export const posters: PosterEntry[] = [
  {
    slug: "e-i-xchange24-poster-edc",
    title: "E(I)Xchange24 Poster EDC",
    path: "/talks/posters/E(i)xchange24_Poster_EDC.pdf",
  },
  {
    slug: "edc-poster-isws2024-award-winner",
    title: "EDC Poster ISWS2024(Award Winner)",
    path: "/talks/posters/EDC_Poster_ISWS2024(award_winner).pdf",
  },
  {
    slug: "eswc-24-poster-edc",
    title: "ESWC 24 Poster EDC",
    path: "/talks/posters/ESWC_24_Poster_EDC.pdf",
  },
  {
    slug: "swat4hcls-2025",
    title: "Swat4hcls 2025",
    path: "/talks/posters/swat4hcls_2025.pdf",
  },
  {
    slug: "swat4hcls-24-poster-edc",
    title: "SWAT4HCLS 24 Poster EDC",
    path: "/talks/posters/SWAT4HCLS_24_poster_EDC.pdf",
  },
];
