/* eslint-disable */
// This file is auto-generated by scripts/build-slides.mjs
// Run: npm run build:slides

export interface TalkEntry {
  slug: string;
  title: string;
  sourceFile: string;
  dateIso: string;
  dateLabel: string;
  slidePath: string;
  posterPath?: string;
  posterTitle?: string;
}

export interface PosterEntry {
  slug: string;
  title: string;
  path: string;
}

export const talks: TalkEntry[] = [
  {
    slug: "18m-vito-internal-jury",
    title: "EDC 18m VITO Jury",
    sourceFile: "EDC-18m-VITO-Jury.pdf",
    dateIso: "2025-11-20",
    dateLabel: "2025",
    slidePath: "/talks/slides/18m-vito-internal-jury.pdf",
  },
  {
    slug: "dph-day-talk",
    title: "EDC DPH 25",
    sourceFile: "EDC-DPH-25.pdf",
    dateIso: "2025-10-10",
    dateLabel: "2025",
    slidePath: "/talks/slides/dph-day-talk.pdf",
  },
  {
    slug: "solid-intro-triple-consortium",
    title: "Solid Intro TRIPLE",
    sourceFile: "Solid_intro_TRIPLE.pdf",
    dateIso: "2025-10-10",
    dateLabel: "2024",
    slidePath: "/talks/slides/solid-intro-triple-consortium.pdf",
  },
  {
    slug: "sib-researchstay-reflection",
    title: "SIB ReflectionUGent",
    sourceFile: "SIB-ReflectionUGent.pdf",
    dateIso: "2025-05-015",
    dateLabel: "2025",
    slidePath: "/talks/slides/sib-researchstay-reflection.pdf",
  },
  {
    slug: "sphn-pengquin-talk",
    title: "SPHN 290425",
    sourceFile: "SPHN-290425.pdf",
    dateIso: "2025-04-29",
    dateLabel: "29/04/2025",
    slidePath: "/talks/slides/sphn-pengquin-talk.pdf",
  },
  {
    slug: "sib-vital-it-talk",
    title: "Vital IT EDC 040425",
    sourceFile: "Vital-IT-EDC-040425.pdf",
    dateIso: "2025-04-04",
    dateLabel: "04/04/2025",
    slidePath: "/talks/slides/sib-vital-it-talk.pdf",
  },
  {
    slug: "swissprot-talk",
    title: "SwissProt",
    sourceFile: "SwissProt.pdf",
    dateIso: "2025-03-25",
    dateLabel: "2025",
    slidePath: "/talks/slides/swissprot-talk.pdf",
  },
  {
    slug: "fwo-interview",
    title: "FWO24 Pitch EDC(Official)",
    sourceFile: "FWO24_Pitch_EDC(official).pdf",
    dateIso: "2024-09-05",
    dateLabel: "2024",
    slidePath: "/talks/slides/fwo-interview.pdf",
  },
  {
    slug: "isws-group-project-presentation",
    title: "ISWS2024 Slytherin Presentation",
    sourceFile: "ISWS2024_Slytherin_Presentation.pdf",
    dateIso: "2024-06-15",
    dateLabel: "2024",
    slidePath: "/talks/slides/isws-group-project-presentation.pdf",
  },
  {
    slug: "eswc-phdsymp-pangquin",
    title: "PENGQUIN ESWC 2024",
    sourceFile: "PENGQUIN_ESWC_2024.pdf",
    dateIso: "2024-05-28",
    dateLabel: "2024",
    slidePath: "/talks/slides/eswc-phdsymp-pangquin.pdf",
    posterPath: "/talks/posters/ESWC_24_Poster_EDC.pdf",
    posterTitle: "ESWC 24 Poster EDC",
  },
  {
    slug: "solidsymp-genomepods",
    title: "SolidSymp2024 EDC",
    sourceFile: "SolidSymp2024_EDC.pdf",
    dateIso: "2024-04-02",
    dateLabel: "2024",
    slidePath: "/talks/slides/solidsymp-genomepods.pdf",
  },
  {
    slug: "ugent-genomics-talk",
    title: "UGent PENGQUIN Intro",
    sourceFile: "UGent_PENGQUIN_Intro.pdf",
    dateIso: "2024-03-04",
    dateLabel: "2024",
    slidePath: "/talks/slides/ugent-genomics-talk.pdf",
  },
];

export const posters: PosterEntry[] = [
  {
    slug: "e-i-xchange24-poster-edc",
    title: "E(I)Xchange24 Poster EDC",
    path: "/talks/posters/E(i)xchange24_Poster_EDC.pdf",
  },
  {
    slug: "edc-poster-isws2024-award-winner",
    title: "EDC Poster ISWS2024(Award Winner)",
    path: "/talks/posters/EDC_Poster_ISWS2024(award_winner).pdf",
  },
  {
    slug: "eswc-24-poster-edc",
    title: "ESWC 24 Poster EDC",
    path: "/talks/posters/ESWC_24_Poster_EDC.pdf",
  },
  {
    slug: "swat4hcls-2025",
    title: "Swat4hcls 2025",
    path: "/talks/posters/swat4hcls_2025.pdf",
  },
  {
    slug: "swat4hcls-24-poster-edc",
    title: "SWAT4HCLS 24 Poster EDC",
    path: "/talks/posters/SWAT4HCLS_24_poster_EDC.pdf",
  },
];
